# Generated by Django 4.2.7 on 2023-11-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_filmowe', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_filmowe.movie'),
        ),
    ]
