# Generated by Django 4.2.7 on 2024-01-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_filmowe', '0003_post_image_like'),
        ('forum_filmowe', '0003_post_movie'),
    ]

    operations = [
    ]
